var LiveReloadPlugin = require('webpack-livereload-plugin');

module.exports = {
  entry: './src-web/index.ts',
  devtool: 'inline-source-map',
  output: {
    filename: 'bundle.js',
    path: __dirname + '/build',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.rs$/,
        use: {
          loader: './rust-loader.js',
          options: {
            // The path to the webpack output relative to the project root
            path: 'build'
          }
        }
      }
    ]
  },
  resolve: {
    extensions: [ ".tsx", ".ts", ".js" , ".rs"]
  },
  // The .wasm 'glue' code generated by Emscripten requires these node builtins,
  // but won't actually use them in a web environment. We tell Webpack to not resolve those
  // require statements since we know we won't need them.
  plugins: [
      new LiveReloadPlugin({})
  ],
  externals: {
    'fs': true,
    'path': true,
  }
}